export enum META_PLANS {
  NEW_SUBJECT_PLAN = 'PLAN DE ASIGNATURA PROPUESTO',
  OLD_SUBJECT_PLAN = 'PLAN DE ASIGNATURA ACTUAL',
}
export enum META_AREAS {
  BASIC_SICENCES = 'CIENCAS BASICAS',
  BASIC_ENGINEERING_SCIENCES = 'CIENCIAS BASICAS DE LA INGENIERIA',
  APPLIED_ENGINEERING = 'INGENIERIA APLICADA',
  INVESTIGATION = 'AREA INVESTIGACION',
  COMPLEMENTARY_AND_INSTITUTIONAL = 'AREA COMPLEMENTARIA E INSTITUCIONAL',
}
