import { META_AREAS } from './meta-data';

export const NEW_SUBJECT_PLAN_DATA = [
  {
    name: 'Cálculo Diferencial',
    semester: 2,
    credits: 3,
    area: META_AREAS.BASIC_SICENCES,
  },
  {
    name: 'Cálculo Integral',
    semester: 3,
    credits: 3,
    area: META_AREAS.BASIC_SICENCES,
  },
  {
    name: 'Cálculo Multivariable',
    semester: 4,
    credits: 3,
    area: META_AREAS.BASIC_SICENCES,
  },
  {
    name: 'Ecuaciones diferenciales',
    semester: 5,
    credits: 3,
    area: META_AREAS.BASIC_SICENCES,
  },
  {
    name: 'Electromagnetismo',
    semester: 3,
    credits: 3,
    area: META_AREAS.BASIC_SICENCES,
  },
  {
    name: 'Matemáticas',
    semester: 1,
    credits: 3,
    area: META_AREAS.BASIC_SICENCES,
  },
  {
    name: 'Mecánica',
    semester: 2,
    credits: 3,
    area: META_AREAS.BASIC_SICENCES,
  },
  {
    name: 'Ondas',
    semester: 4,
    credits: 3,
    area: META_AREAS.BASIC_SICENCES,
  },
  {
    name: 'Álgebra Lineal',
    semester: 2,
    credits: 3,
    area: META_AREAS.BASIC_ENGINEERING_SCIENCES,
  },
  {
    name: 'Análisis Numérico',
    semester: 6,
    credits: 3,
    area: META_AREAS.BASIC_ENGINEERING_SCIENCES,
  },
  {
    name: 'Circuitos',
    semester: 5,
    credits: 3,
    area: META_AREAS.BASIC_ENGINEERING_SCIENCES,
  },
  {
    name: 'Estadística descriptiva e inferencial',
    semester: 3,
    credits: 3,
    area: META_AREAS.BASIC_ENGINEERING_SCIENCES,
  },
  {
    name: 'Investigación de Operaciones',
    semester: 7,
    credits: 3,
    area: META_AREAS.BASIC_ENGINEERING_SCIENCES,
  },
  {
    name: 'Lógica Matemática',
    semester: 1,
    credits: 3,
    area: META_AREAS.BASIC_ENGINEERING_SCIENCES,
  },
  {
    name: 'Algoritmos y fundamentos de programación',
    semester: 1,
    credits: 3,
    area: META_AREAS.APPLIED_ENGINEERING,
  },
  {
    name: 'Arquitectura del Computador',
    semester: 6,
    credits: 3,
    area: META_AREAS.APPLIED_ENGINEERING,
  },
  {
    name: 'Base de Datos',
    semester: 5,
    credits: 3,
    area: META_AREAS.APPLIED_ENGINEERING,
  },
  {
    name: 'Base de Datos Avanzadas',
    semester: 6,
    credits: 3,
    area: META_AREAS.APPLIED_ENGINEERING,
  },
  {
    name: 'Computación en la nube',
    semester: 8,
    credits: 3,
    area: META_AREAS.APPLIED_ENGINEERING,
  },
  {
    name: 'Diseño Gráfico',
    semester: 4,
    credits: 1,
    area: META_AREAS.APPLIED_ENGINEERING,
  },
  {
    name: 'Electiva de Profundización I',
    semester: 9,
    credits: 3,
    area: META_AREAS.APPLIED_ENGINEERING,
  },
  {
    name: 'Electiva de Profundización II',
    semester: 10,
    credits: 3,
    area: META_AREAS.APPLIED_ENGINEERING,
  },
  {
    name: 'Electiva del Programa I',
    semester: 8,
    credits: 3,
    area: META_AREAS.APPLIED_ENGINEERING,
  },
  {
    name: 'Electiva del Programa II',
    semester: 9,
    credits: 3,
    area: META_AREAS.APPLIED_ENGINEERING,
  },
  {
    name: 'Estructura de Datos',
    semester: 4,
    credits: 3,
    area: META_AREAS.APPLIED_ENGINEERING,
  },
  {
    name: 'Formulación y evaluación de proyectos de Ingeniería',
    semester: 8,
    credits: 3,
    area: META_AREAS.APPLIED_ENGINEERING,
  },
  {
    name: 'Gestión de proyectos TI',
    semester: 9,
    credits: 3,
    area: META_AREAS.APPLIED_ENGINEERING,
  },
  {
    name: 'Ingeniería de Software I',
    semester: 7,
    credits: 3,
    area: META_AREAS.APPLIED_ENGINEERING,
  },
  {
    name: 'Ingeniería de Software II',
    semester: 8,
    credits: 3,
    area: META_AREAS.APPLIED_ENGINEERING,
  },
  {
    name: 'Inteligencia Artificial',
    semester: 9,
    credits: 3,
    area: META_AREAS.APPLIED_ENGINEERING,
  },
  {
    name: 'Inteligencia de negocios',
    semester: 7,
    credits: 3,
    area: META_AREAS.APPLIED_ENGINEERING,
  },
  {
    name: 'Introducción a la Ingeniería de Sistemas',
    semester: 1,
    credits: 2,
    area: META_AREAS.APPLIED_ENGINEERING,
  },
  {
    name: 'Modelamiento y Simulación',
    semester: 9,
    credits: 3,
    area: META_AREAS.APPLIED_ENGINEERING,
  },
  {
    name: 'Pensamiento Sistémico',
    semester: 3,
    credits: 2,
    area: META_AREAS.APPLIED_ENGINEERING,
  },
  {
    name: 'Programación de computadores I',
    semester: 2,
    credits: 3,
    area: META_AREAS.APPLIED_ENGINEERING,
  },
  {
    name: 'Programación de computadores II',
    semester: 3,
    credits: 3,
    area: META_AREAS.APPLIED_ENGINEERING,
  },
  {
    name: 'Programación de computadores III',
    semester: 4,
    credits: 3,
    area: META_AREAS.APPLIED_ENGINEERING,
  },
  {
    name: 'Programación Web',
    semester: 5,
    credits: 3,
    area: META_AREAS.APPLIED_ENGINEERING,
  },
  {
    name: 'Fundamentos de Redes Informáticas',
    semester: 6,
    credits: 3,
    area: META_AREAS.APPLIED_ENGINEERING,
  },
  {
    name: 'Optimización de Redes Informáticas',
    semester: 7,
    credits: 3,
    area: META_AREAS.APPLIED_ENGINEERING,
  },
  {
    name: 'Seguridad y Privacidad Información',
    semester: 8,
    credits: 3,
    area: META_AREAS.APPLIED_ENGINEERING,
  },
  {
    name: 'Sistemas Operativos',
    semester: 7,
    credits: 3,
    area: META_AREAS.APPLIED_ENGINEERING,
  },
  {
    name: 'Tecnologías Inmersivas',
    semester: 5,
    credits: 3,
    area: META_AREAS.APPLIED_ENGINEERING,
  },
  {
    name: 'Programación Móviles',
    semester: 6,
    credits: 3,
    area: META_AREAS.APPLIED_ENGINEERING,
  },
  {
    name: 'Innovación y emprendimiento tecnológico',
    semester: 6,
    credits: 2,
    area: META_AREAS.INVESTIGATION,
  },
  {
    name: 'Metodología de Investigación',
    semester: 4,
    credits: 2,
    area: META_AREAS.INVESTIGATION,
  },
  {
    name: 'Proyecto de Grado I',
    semester: 9,
    credits: 2,
    area: META_AREAS.INVESTIGATION,
  },
  {
    name: 'Proyecto de Grado II',
    semester: 10,
    credits: 2,
    area: META_AREAS.INVESTIGATION,
  },
  {
    name: 'Research Project',
    semester: 7,
    credits: 2,
    area: META_AREAS.INVESTIGATION,
  },
  {
    name: 'Semillero de Investigación',
    semester: 3,
    credits: 2,
    area: META_AREAS.INVESTIGATION,
  },
  {
    name: 'Seminario de Investigación',
    semester: 5,
    credits: 2,
    area: META_AREAS.INVESTIGATION,
  },
  {
    name: 'Ética Profesional',
    semester: 9,
    credits: 1,
    area: META_AREAS.COMPLEMENTARY_AND_INSTITUTIONAL,
  },
  {
    name: 'Legislación Tecnológica',
    semester: 8,
    credits: 1,
    area: META_AREAS.COMPLEMENTARY_AND_INSTITUTIONAL,
  },
  {
    name: 'Formación Ciudadana y Constitucional',
    semester: 7,
    credits: 1,
    area: META_AREAS.COMPLEMENTARY_AND_INSTITUTIONAL,
  },
  {
    name: 'Tech English I',
    semester: 5,
    credits: 1,
    area: META_AREAS.COMPLEMENTARY_AND_INSTITUTIONAL,
  },
  {
    name: 'Tech English II',
    semester: 6,
    credits: 1,
    area: META_AREAS.COMPLEMENTARY_AND_INSTITUTIONAL,
  },
  {
    name: 'Actividad Deportiva',
    semester: 3,
    credits: 1,
    area: META_AREAS.COMPLEMENTARY_AND_INSTITUTIONAL,
  },
  {
    name: 'Actividad Cultural',
    semester: 2,
    credits: 1,
    area: META_AREAS.COMPLEMENTARY_AND_INSTITUTIONAL,
  },
  {
    name: 'Cátedra Ambiental y Desarrollo Sostenible',
    semester: 4,
    credits: 1,
    area: META_AREAS.COMPLEMENTARY_AND_INSTITUTIONAL,
  },
  {
    name: 'Cátedra de la paz',
    semester: 3,
    credits: 1,
    area: META_AREAS.COMPLEMENTARY_AND_INSTITUTIONAL,
  },
  {
    name: 'Cátedra Upecista',
    semester: 1,
    credits: 1,
    area: META_AREAS.COMPLEMENTARY_AND_INSTITUTIONAL,
  },
];
