import { META_AREAS } from 'src/curriculum/constants';

export const OLD_SUBJECT_PLAN_DATA = [
  {
    name: 'CALCULO I',
    semester: 1,
    credits: 4,
    area: META_AREAS.BASIC_SICENCES,
  },
  {
    name: 'CALCULO II',
    semester: 2,
    credits: 3,
    area: META_AREAS.BASIC_SICENCES,
  },
  {
    name: 'CALCULO III',
    semester: 3,
    credits: 3,
    area: META_AREAS.BASIC_SICENCES,
  },
  {
    name: 'CALCULO IV',
    semester: 4,
    credits: 3,
    area: META_AREAS.BASIC_SICENCES,
  },
  {
    name: 'FISICA III',
    semester: 4,
    credits: 3,
    area: META_AREAS.BASIC_SICENCES,
  },
  {
    name: 'FISICA I',
    semester: 2,
    credits: 3,
    area: META_AREAS.BASIC_SICENCES,
  },
  {
    name: 'FISICA II',
    semester: 3,
    credits: 3,
    area: META_AREAS.BASIC_SICENCES,
  },
  {
    name: 'ALGEBRA LINEAL',
    semester: 2,
    credits: 2,
    area: META_AREAS.BASIC_ENGINEERING_SCIENCES,
  },
  {
    name: 'ANALISIS NUMERICO',
    semester: 5,
    credits: 3,
    area: META_AREAS.BASIC_ENGINEERING_SCIENCES,
  },
  {
    name: 'CIRCUITOS',
    semester: 5,
    credits: 3,
    area: META_AREAS.BASIC_ENGINEERING_SCIENCES,
  },
  {
    name: 'ESTADISTICA',
    semester: 4,
    credits: 3,
    area: META_AREAS.BASIC_ENGINEERING_SCIENCES,
  },
  {
    name: 'INVESTIGACIÓN DE OPERACIONES I',
    semester: 6,
    credits: 3,
    area: META_AREAS.BASIC_ENGINEERING_SCIENCES,
  },
  {
    name: 'LÓGICA MATEMÁTICA',
    semester: 1,
    credits: 2,
    area: META_AREAS.BASIC_ENGINEERING_SCIENCES,
  },
  {
    name: 'EXPRESION GRAFICA',
    semester: 1,
    credits: 2,
    area: META_AREAS.BASIC_ENGINEERING_SCIENCES,
  },
  {
    name: 'INVESTIGACIÓN DE OPERACIONES II',
    semester: 7,
    credits: 3,
    area: META_AREAS.BASIC_ENGINEERING_SCIENCES,
  },
  {
    name: 'FUNDAMENTOS DE PROGRAMACIÓN',
    semester: 1,
    credits: 3,
    area: META_AREAS.APPLIED_ENGINEERING,
  },
  {
    name: 'ARQUITECTURA DEL COMPUTADOR.',
    semester: 6,
    credits: 3,
    area: META_AREAS.APPLIED_ENGINEERING,
  },
  {
    name: 'BASE DE DATOS I',
    semester: 5,
    credits: 3,
    area: META_AREAS.APPLIED_ENGINEERING,
  },
  {
    name: 'SERVIDORES',
    semester: 8,
    credits: 3,
    area: META_AREAS.APPLIED_ENGINEERING,
  },
  {
    name: 'DISEÑO GRÁFICO',
    semester: 3,
    credits: 2,
    area: META_AREAS.APPLIED_ENGINEERING,
  },
  {
    name: 'ELECTIVA DEL PROGRAMA I',
    semester: 9,
    credits: 3,
    area: META_AREAS.APPLIED_ENGINEERING,
  },
  {
    name: 'ELECTIVA DEL PROGRAMA II',
    semester: 10,
    credits: 3,
    area: META_AREAS.APPLIED_ENGINEERING,
  },
  {
    name: 'ESTRUCTURA DE DATOS',
    semester: 4,
    credits: 3,
    area: META_AREAS.APPLIED_ENGINEERING,
  },
  {
    name: 'INGENIERIA DEL SOFTWARE I',
    semester: 6,
    credits: 3,
    area: META_AREAS.APPLIED_ENGINEERING,
  },
  {
    name: 'INGENIERIA DEL SOFTWAREII',
    semester: 7,
    credits: 3,
    area: META_AREAS.APPLIED_ENGINEERING,
  },
  {
    name: 'INTELIGENCIA DE NEGOCIOS',
    semester: 6,
    credits: 3,
    area: META_AREAS.APPLIED_ENGINEERING,
  },
  {
    name: 'INTRODUCCIONA LA INGENIERIA DE SISTEMAS',
    semester: 1,
    credits: 2,
    area: META_AREAS.APPLIED_ENGINEERING,
  },
  {
    name: 'MODELAMIENTO Y SIMULACIÓN',
    semester: 8,
    credits: 3,
    area: META_AREAS.APPLIED_ENGINEERING,
  },
  {
    name: 'PENSAMIENTO SISTÉMICO',
    semester: 3,
    credits: 2,
    area: META_AREAS.APPLIED_ENGINEERING,
  },
  {
    name: 'PROGRAMACIÓN I',
    semester: 2,
    credits: 3,
    area: META_AREAS.APPLIED_ENGINEERING,
  },
  {
    name: 'PROGRAMACIÓN II',
    semester: 3,
    credits: 3,
    area: META_AREAS.APPLIED_ENGINEERING,
  },
  {
    name: 'PROGRAMACIÓN III',
    semester: 4,
    credits: 3,
    area: META_AREAS.APPLIED_ENGINEERING,
  },
  {
    name: 'PROGRAMACIÓN IV',
    semester: 5,
    credits: 3,
    area: META_AREAS.APPLIED_ENGINEERING,
  },
  {
    name: 'REDES Y TELECOMUNICACIONES',
    semester: 6,
    credits: 4,
    area: META_AREAS.APPLIED_ENGINEERING,
  },
  {
    name: 'REDES Y TELECOMUNICACIONES II',
    semester: 7,
    credits: 4,
    area: META_AREAS.APPLIED_ENGINEERING,
  },
  {
    name: 'SEGURIDAD Y PRIVACIDAD DE LA INFORMACIÓN',
    semester: 7,
    credits: 3,
    area: META_AREAS.APPLIED_ENGINEERING,
  },
  {
    name: 'SISTEMAS OPERATIVOS',
    semester: 7,
    credits: 3,
    area: META_AREAS.APPLIED_ENGINEERING,
  },
  {
    name: 'PROFUNDIZACIÓN BI',
    semester: 9,
    credits: 3,
    area: META_AREAS.APPLIED_ENGINEERING,
  },
  {
    name: 'PROFUNDIZACIÓN AII',
    semester: 10,
    credits: 3,
    area: META_AREAS.APPLIED_ENGINEERING,
  },
  {
    name: 'PROFUNDIZACIÓN BII',
    semester: 10,
    credits: 3,
    area: META_AREAS.APPLIED_ENGINEERING,
  },
  {
    name: 'SOFTWARE EDUCATIVO',
    semester: 9,
    credits: 3,
    area: META_AREAS.APPLIED_ENGINEERING,
  },
  {
    name: 'PROFUNDIZACIÓN AI',
    semester: 9,
    credits: 3,
    area: META_AREAS.APPLIED_ENGINEERING,
  },
  {
    name: 'SISTEMAS BASADOS EN EL CONOCIMIENTO',
    semester: 8,
    credits: 4,
    area: META_AREAS.APPLIED_ENGINEERING,
  },
  {
    name: 'METODOLOGIA DE INVESTIGACION',
    semester: 5,
    credits: 2,
    area: META_AREAS.INVESTIGATION,
  },
  {
    name: 'PROYECTO DE GRADO I',
    semester: 9,
    credits: 2,
    area: META_AREAS.INVESTIGATION,
  },
  {
    name: 'PROYECTO DE GRADO II',
    semester: 10,
    credits: 2,
    area: META_AREAS.INVESTIGATION,
  },
  {
    name: 'SEMILLEROS DE INVESTIGACION',
    semester: 3,
    credits: 1,
    area: META_AREAS.INVESTIGATION,
  },
  {
    name: 'SEMINARIO DE INVESTIGACIÓN',
    semester: 8,
    credits: 3,
    area: META_AREAS.INVESTIGATION,
  },
  {
    name: 'COMUNICACIÓN ORAL Y ESCRITA I',
    semester: 1,
    credits: 3,
    area: META_AREAS.COMPLEMENTARY_AND_INSTITUTIONAL,
  },
  {
    name: 'COMUNICACIÓN ORAL Y ESCRITA II',
    semester: 2,
    credits: 3,
    area: META_AREAS.COMPLEMENTARY_AND_INSTITUTIONAL,
  },
  {
    name: 'DESARROLLO HUMANO',
    semester: 2,
    credits: 2,
    area: META_AREAS.COMPLEMENTARY_AND_INSTITUTIONAL,
  },
  {
    name: 'ELECTIVA COMPLEMENTARIA',
    semester: 3,
    credits: 2,
    area: META_AREAS.COMPLEMENTARY_AND_INSTITUTIONAL,
  },
  {
    name: 'RESPONSABILIDAD PROFESIONAL',
    semester: 8,
    credits: 2,
    area: META_AREAS.COMPLEMENTARY_AND_INSTITUTIONAL,
  },
  {
    name: 'ESPÍRITU EMPRESARIAL',
    semester: 5,
    credits: 2,
    area: META_AREAS.COMPLEMENTARY_AND_INSTITUTIONAL,
  },
  {
    name: 'FUNDAMENTOS DE ADMINISTRACIÓN',
    semester: 4,
    credits: 2,
    area: META_AREAS.COMPLEMENTARY_AND_INSTITUTIONAL,
  },
  {
    name: 'FUNDAMENTOS CONTABLES',
    semester: 5,
    credits: 2,
    area: META_AREAS.COMPLEMENTARY_AND_INSTITUTIONAL,
  },
  {
    name: 'FUNDAMENTOS DE ECONOMÍA',
    semester: 7,
    credits: 2,
    area: META_AREAS.COMPLEMENTARY_AND_INSTITUTIONAL,
  },
  {
    name: 'MATEMÁTICAS FINANCIERAS',
    semester: 9,
    credits: 3,
    area: META_AREAS.COMPLEMENTARY_AND_INSTITUTIONAL,
  },
  {
    name: 'DERECHO INFORMÁTICO',
    semester: 8,
    credits: 2,
    area: META_AREAS.COMPLEMENTARY_AND_INSTITUTIONAL,
  },
  {
    name: 'DERECHO CONSTITUCIONAL',
    semester: 6,
    credits: 2,
    area: META_AREAS.COMPLEMENTARY_AND_INSTITUTIONAL,
  },
  {
    name: 'LENGUA EXTRANJERA (GRAMATICA)',
    semester: 1,
    credits: 0,
    area: META_AREAS.COMPLEMENTARY_AND_INSTITUTIONAL,
  },
  {
    name: 'LENGUA EXTRANJERA (LECTURA)',
    semester: 2,
    credits: 0,
    area: META_AREAS.COMPLEMENTARY_AND_INSTITUTIONAL,
  },
  {
    name: 'LENGUA EXTRANJERA (ESCRITURA)',
    semester: 3,
    credits: 0,
    area: META_AREAS.COMPLEMENTARY_AND_INSTITUTIONAL,
  },
  {
    name: 'LENGUA EXTRANJERA (CONVERSACION)',
    semester: 4,
    credits: 0,
    area: META_AREAS.COMPLEMENTARY_AND_INSTITUTIONAL,
  },
  {
    name: 'TECHNICAL ENGLISH I',
    semester: 8,
    credits: 2,
    area: META_AREAS.COMPLEMENTARY_AND_INSTITUTIONAL,
  },
  {
    name: 'TECHNICAL ENGLISH II',
    semester: 9,
    credits: 2,
    area: META_AREAS.COMPLEMENTARY_AND_INSTITUTIONAL,
  },
  {
    name: 'ACT. CULTURAL Y DPTIVA I',
    semester: 2,
    credits: 0,
    area: META_AREAS.COMPLEMENTARY_AND_INSTITUTIONAL,
  },
  {
    name: 'ACT. CULTURAL Y DPTIVA II',
    semester: 3,
    credits: 0,
    area: META_AREAS.COMPLEMENTARY_AND_INSTITUTIONAL,
  },
  {
    name: 'CÁTEDRA DE LA PAZ',
    semester: 4,
    credits: 0,
    area: META_AREAS.COMPLEMENTARY_AND_INSTITUTIONAL,
  },
  {
    name: 'CÁTEDRA UPECISTA',
    semester: 1,
    credits: 0,
    area: META_AREAS.COMPLEMENTARY_AND_INSTITUTIONAL,
  },
  {
    name: 'COMERCIO INTERNACIONAL',
    semester: 5,
    credits: 2,
    area: META_AREAS.COMPLEMENTARY_AND_INSTITUTIONAL,
  },
];
